"""Built-in mock executor.

Simulates an agent doing real work so the platform runs end-to-end here without
external CLIs or API keys. It is *not* faked at the seam: it operates on a real
git worktree and produces a real commit + diff, because the architecture's
recoverable fact is the commit, not the agent's in-memory reasoning (arch 3.1).
A Claude Code / OpenCode adapter would slot in behind the same Executor contract.

It emits the full normalized event stream (tool_call/message/progress/result)
so a rich-executor UI path is exercised. Thin adapters would emit only coarse
progress + a final diff; the frontend degrades gracefully either way.
"""
from __future__ import annotations

import asyncio
import hashlib
import subprocess
from pathlib import Path

from ..config import SIM_TICK_SEC
from .base import CapProfile, Emit, ExecResult, Executor, TaskEnvelope


# Role-specific scripted "thought" beats. Deterministic but varied by role so the
# stream reads like real collaboration rather than a spinner.
ROLE_SCRIPT: dict[str, list[tuple[str, str, str]]] = {
    "analyst": [
        ("tool_call", "grep", "检索相关代码与历史工单…"),
        ("message", "", "梳理需求边界，确认验收标准。"),
        ("progress", "", "规格草拟中"),
    ],
    "developer": [
        ("tool_call", "read", "读取相关源码定位改动点…"),
        ("tool_call", "grep", "搜索同类实现作为参考…"),
        ("message", "", "定位到问题，开始修改。"),
        ("tool_call", "edit", "编辑代码并本地验证…"),
        ("progress", "", "提交改动"),
    ],
    "tester": [
        ("tool_call", "bash", "运行单元测试与集成测试…"),
        ("message", "", "补充用例覆盖边界场景。"),
        ("progress", "", "测试通过"),
    ],
    "devops": [
        ("tool_call", "bash", "准备灰度发布流水线…"),
        ("message", "", "蓝绿环境就绪，等待审批后放量。"),
    ],
    "coordinator": [
        ("message", "", "拆解任务并按契约分派。"),
        ("progress", "", "已分派"),
    ],
}


def _git(cwd: str, *args: str) -> str:
    out = subprocess.run(
        ["git", *args], cwd=cwd,
        stdin=subprocess.DEVNULL,
        capture_output=True, text=True,
        encoding="utf-8", errors="replace",
    )
    return (out.stdout or out.stderr or "").strip()


class MockExecutor:
    name = "builtin-mock"
    caps = CapProfile(
        streams_events=True, mcp=True, hooks=True,
        subagents=True, structured_out=True, resume=True,
    )

    async def run(self, env: TaskEnvelope, emit: Emit) -> ExecResult:
        role = env.role
        emit("state", ticket=env.ticket_id, agent=role, payload={"state": "working"})
        emit("message", ticket=env.ticket_id, agent=role,
             payload={"text": f"开始处理：{env.instruction[:60]}"})

        for kind, tool, text in ROLE_SCRIPT.get(role, ROLE_SCRIPT["developer"]):
            await asyncio.sleep(SIM_TICK_SEC)
            if kind == "tool_call":
                emit("tool_call", ticket=env.ticket_id, agent=role,
                     payload={"tool": tool, "text": text})
            else:
                emit(kind, ticket=env.ticket_id, agent=role, payload={"text": text})

        head_sha, diff_ref = "", ""
        # Developers actually mutate the worktree and commit — that's the durable fact.
        if role == "developer" and env.repo.worktree:
            head_sha, diff_ref = self._make_change(env)

        await asyncio.sleep(SIM_TICK_SEC)
        emit("result", ticket=env.ticket_id, agent=role,
             payload={"text": env.done_hint or "已完成本职任务，申请验收。",
                      "head_sha": head_sha})

        # token/cost usage is synthesised from the instruction size for budgeting.
        toks = 1500 + len(env.instruction) * 3
        return ExecResult(
            status="completed",
            head_sha=head_sha,
            diff_ref=diff_ref,
            summary=env.done_hint or "完成",
            usage={"tokens": toks, "cost_usd": round(toks / 1_000 * 0.015, 4), "steps": 6},
        )

    def _make_change(self, env: TaskEnvelope) -> tuple[str, str]:
        """Write a real fix file into the worktree and commit it."""
        wt = Path(env.repo.worktree)
        wt.mkdir(parents=True, exist_ok=True)
        if not (wt / ".git").exists():
            _git(str(wt), "init", "-q")
            _git(str(wt), "config", "user.email", "agent@warroom.local")
            _git(str(wt), "config", "user.name", "warroom-agent")
            (wt / "README.md").write_text("# workspace\n", encoding="utf-8")
            _git(str(wt), "add", "-A")
            _git(str(wt), "commit", "-qm", "init")

        # Synthesise a deterministic but ticket-specific change.
        slug = hashlib.md5(env.ticket_id.encode()).hexdigest()[:8]
        fix = wt / f"fix_{env.ticket_id}.py"
        fix.write_text(
            f'"""Fix for {env.ticket_id}: {env.meta.get("title","")}\n'
            f'Generated by {self.name} ({slug})."""\n\n'
            "def apply():\n"
            "    # paginated/streamed implementation + index, validated locally\n"
            "    return True\n",
            encoding="utf-8",
        )
        _git(str(wt), "add", "-A")
        _git(str(wt), "commit", "-qm", f"fix({env.ticket_id}): {env.meta.get('title','change')}")
        head = _git(str(wt), "rev-parse", "HEAD")
        diff = _git(str(wt), "show", "--stat", "--oneline", "HEAD")
        return head, diff


# Registry so the engine / config can pick an executor by display name.
def build_registry() -> dict[str, Executor]:
    mock = MockExecutor()
    # All named executors map to the mock implementation in this MVP; the seam
    # is real (same contract), only the backend behind it is simulated.
    return {
        "内置 Agent SDK": mock,
        "Claude Code": mock,
        "OpenCode": mock,
        "通用 CLI": mock,
    }
